[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4.10.2"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.219", features = ["derive"] }
config = "0.15.11"
uuid = { version = "1.16.0", features = ["v4"] }
chrono = "0.4.40"
log = "0.4.26"
tracing = {version = "0.1.41", features = ["log"]}
tracing-subscriber = {version = "0.3.19", features = ["registry", "env-filter"]}
tracing-bunyan-formatter = "0.3.10"
tracing-log = "0.2.0"
secrecy = {version = "0.10.3", features = ["serde"]}
tracing-actix-web = "0.7.16"


[dependencies.sqlx]
version = "0.8.3"
default-features = false
features = ["runtime-tokio-rustls",
    "macros",
"postgres",
"uuid",
"chrono",
"migrate"]

[dev-dependencies]
reqwest = "0.12.15"
once_cell = "1.21.1"